version: "3"
services:
  notebook:
    image: jupyter/all-spark-notebook
    labels:
      description: Spark using Jupyter Notebooks
      name: jupyter notebook 
    ports:
      - "8888:8888"
    volumes:
      - $PWD/notebooks:/home/notebooks
   